language: python
python: 2.7
sudo: false
os:
  - linux

cache:
  directories:
    - $HOME/.cache/pip/

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - chmod 755 /opt

script:
  - nosetests -v
